name: Min första workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Hämta koden
        uses: actions/checkout@v5

      - name: Skriv ut ett meddelande
        run: echo "Hej! Min GitHub Action fungerar!"

      - name: min loop
        run: |
          for i in 1 2 3 4 5
          do 
          echo "Nummer: $i"
          done

      - name: Visa branch-namn
        run: |
         echo "kor på branch: $GITHUB_REF"